name: smart-gym-cloud
services:
  postgres-db:
    image: postgres:16-alpine
    container_name: smart-access-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-cache:
    image: redis:7-alpine
    container_name: smart-access-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: smart_gym_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: smart-gym-zipkin
    ports:
      - "9411:9411"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9411/health" ]
      interval: 5s
      timeout: 5s
      retries: 5

  smart-gym-gateway:
    build: ./smart-gym-gateway
    container_name: smart-gym-gateway
    ports:
      - "8000:8000"
    depends_on:
      - smart-gym-core
      - smart-gym-auth
      - smart-gym-client
      - smart-gym-notification
    environment:
      - AUTH_SERVICE_URL=http://smart-gym-auth:8083
      - CORE_SERVICE_URL=http://smart-gym-core:8080
      - CLIENT_SERVICE_URL=http://smart-gym-client:8082
      - NOTIFICATION_SERVICE_URL=http://smart-gym-notification:8081
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans

  smart-gym-core:
    build: ./smart-gym-core
    container_name: smart-gym-core
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/smart_access_core
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_SERVICE_URL=${CLIENT_SERVICE_URL}
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans

  smart-gym-auth:
    build: ./smart-gym-auth
    container_name: smart-gym-auth
    ports:
      - "8083:8083"
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/smart_access_auth
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - JWT_REFRESH_EXPIRATION_DAYS=${JWT_REFRESH_EXPIRATION_DAYS}
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans

  smart-gym-client:
    build: ./smart-gym-client
    container_name: smart-gym-client
    ports:
      - "8082:8082"
    depends_on:
      postgres-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - DB_URL=jdbc:postgresql://postgres-db:5432/smart_access_client
      - DB_USER=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans

  smart-gym-notification:
    build: ./smart-gym-notification
    container_name: smart-gym-notification
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - INTEGRATION_CRM_BASE_URL=${INTEGRATION_CRM_BASE_URL}
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans

#PROMETHEUS & GRAFANA METRIC FOR PROJECT
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: smart-gym-prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
#    depends_on:
#      - smart-gym-app
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: smart-gym-grafana
#    ports:
#      - "3000:3000"
#    environment:
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - grafana_data:/var/lib/grafana
#    depends_on:
#      - prometheus
#
#ADMINER USED FOR WEB-VIEWER DB
#  adminer:
#    image: adminer
#    container_name: adminer
#    ports:
#      - "8081:8080"
#    depends_on:
#      - postgres-db
      
volumes:
  postgres_data:
  rabbitmq_data:
#  prometheus_data:
#  grafana_data: