server:
  port: 8083

spring:
  output:
    ansi:
      enabled: ALWAYS
  threads:
    virtual:
      enabled: true

  application:
    name: smart-gym-auth

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/smart_access_auth}
    username: ${DB_USER:danek}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
              - user:email
              - read:user

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh-expiration-days: ${JWT_REFRESH_EXPIRATION_DAYS}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}

  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

logging:
  include-application-name: false
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${spring.application.name:-}){cyan} %clr([%X{traceId:-},%X{spanId:-}]){magenta} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
