server:
  port: 8081

spring:

  output:
    ansi:
      enabled: ALWAYS

  threads:
    virtual:
      enabled: true

  application:
    name: smart-gym-notification

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:danek}
    password: ${SPRING_RABBITMQ_PASSWORD:admin}
    template:
      observation-enabled: true
    listener:
      simple:
        observation-enabled: true

integration:
  crm:
    base-url: ${INTEGRATION_CRM_BASE_URL:https://postman-echo.com}
#    https://postman-echo.com working service

app:
  rabbitmq:
    exchange: "gym.events"
    routing-key: "gym.access.registered"
    binding-pattern: "gym.access.*"
    queue: "gym.notifications.queue"
    dlx: "gym.dlx"
    dlq: "gym.notifications.dlq.queue"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
    export:
      zipkin:
        endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

resilience4j:
  circuitbreaker:
    instances:
      crmService:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.web.client.RestClientException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
  retry:
    instances:
      crmService:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - org.springframework.web.client.HttpServerErrorException

logging:
  include-application-name: false
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}] "
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${spring.application.name:-}){cyan} %clr([%X{traceId:-},%X{spanId:-}]){magenta} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
